<?xml version="1.0" encoding="utf-8"?><Database Name="bazadanych" Class="bazadanychDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\gameo\source\repos\BD_here\bazadanych.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="cryptoUI.Properties.Settings" SettingsPropertyName="bazadanychConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Prices" Member="Prices">
    <Type Name="Price">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Price" Member="Price1" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Currency_Price" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Currency_Price" Member="Prices" ThisKey="Id" OtherKey="CurrencyId" Type="Price" />
    </Type>
  </Table>
</Database>