<?xml version="1.0" encoding="utf-8"?><Database Name="bazadanych" Class="bazadanychDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\gameo\source\repos\BD_here\bazadanych.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="cryptoUI.Properties.Settings" SettingsPropertyName="bazadanychConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Currencies" Member="Currencies">
    <Type Name="Currency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="API_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Currency_Table" Member="Tables" ThisKey="Id" OtherKey="Id_Currency" Type="Table" />
    </Type>
  </Table>
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="DataTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Currency_Table" Member="Currency" ThisKey="Id_Currency" OtherKey="Id" Type="Currency" IsForeignKey="true" />
    </Type>
  </Table>
</Database>